### ISSUE TITLE
Unable to send data to multiple Vtube Studio instances

### ISSUE THREAD

**Issue by NovaAndPulse** [Z-Ray-Entertainment/Facetracker#15]
FaceTracker has been working fantastic so far and has been key to getting Live2D running on Linux for me.

The first instance of VTube Studio picked up the camera flawlessly.
However, once I start up a second instance (from the first), that second instance has no access to the camera.

I'm running version 24.10, installed from Flathub.

Attached is my Debug Information.
Note that I have an Elgato USB capture card connected.
[FacetrackerDebug.txt](https://github.com/user-attachments/files/17920603/FacetrackerDebug.txt)

Thanks for this amazing piece of work that greatly simplifies how we run face tracking on Linux.

**Comment by VortexAcherontic** [comment]
Thank you for the kind feedback. I really appreciate it. ❤️ 

Unfortunately I have to confirm that this behavior is "expected" not that I am happy with this either. Facetracker is launching OpenSeeFace in the background which does all the tracking things. Which unfortunately has the limitation that it only provides the tracking data to one client hence the first VTube Studio instance.

At this point I am not sure if it is even possible to somehow "hack" it to support multiple VTubbing applications accessing the tracking data.

A possible workaround for now could be to shim an additional software in between which gets the tracking data from Facetracker but in return can send these tracking data to any number of additional clients. Similar to how I explained to setup and use Warudo on Linux in this video: https://youtu.be/H0YotaNSbDc?t=363&feature=shared

But I am unaware of any software which could do this. I am very sorry :/

**Comment by NovaAndPulse** [comment]
Thank you for the detailed response.
I was worried it was a limitation beyond this application's scope.

I will explore some other workarounds and report my findings.

This is only one of the _several_ challenges I have to handle for my specific setup,
so one way or another I will find a solution, even if it isn't ideal.

**Comment by VortexAcherontic** [comment]
Thank you I'll keep an eye open for this as well and let you know. Closing the issue for now as this is nothing I can fix at this point 😞
